// react-pomodoro/src/presentation/core/components/input.js
function Input(props) {
  return (
    <div className="form-group mb-3">
      <label for={props.label}>{props.label}:</label>
      <input type={props.inputType} className="form-control" id={props.label} placeholder={props.label} name={props.label} onChange={(e) => props.onClick(e.target.value) } />
    </div>
  )
}

export default Input

// vue-pomodoro/src/presentation/core/components/Input.vue
<template>
  <div class="form-group mb-3">
    <label :for="label">{{ label }}:</label>
    <input v-model="value" :type="inputType" class="form-control" :id="label" :placeholder="label" :name="label" />
  </div>
</template>

<script>
export default {
  props: {
    label: {
      type: String,
      default: () => ''
    },
    inputType: {
      type: String,
      default: () => ''
    },
    onClick: {
      type: Function,
      default: () => (() => {})
    }
  },
  data() {
    return {
      value: ''
    }
  },
  watch: {
    value(newValue, oldValue) {
      this.onClick(this.value)
    }
  }
}
</script>

<style>
/* EMPTY */
</style>
