// react-pomodoro/src/App.js
import { BrowserRouter, Route, Switch } from 'react-router-dom'

import "../node_modules/bootstrap/dist/css/bootstrap.css"

import LoginPage from './presentation/auth/page/login_page'
import RegisterPage from './presentation/auth/page/register_page'
import PomodoroPage from './presentation/pomodoro/page/pomodoro_page'
import NewTaskPage from './presentation/pomodoro/page/new_task_page'
import './App.css';

function App() {
  return (
    <BrowserRouter>
      <Switch>
        <Route path='/new-task' component={NewTaskPage}></Route>
        <Route path='/pomodoro' component={PomodoroPage}></Route>
        <Route path='/register' component={RegisterPage}></Route>
        <Route path='/' component={LoginPage}></Route>
      </Switch>
    </BrowserRouter>
  );
}

export default App;

// svelte-pomodoro/src/App.svelte
<script>
  import page from "page"

  import LoginPage from "./presentation/auth/pages/LoginPage.svelte"
  import RegisterPage from "./presentation/auth/pages/RegisterPage.svelte"
  import PomodoroPage from "./presentation/pomodoro/pages/PomodoroPage.svelte"
  import NewTask from "./presentation/pomodoro/pages/NewTask.svelte"

  let baseURL = '/'
  let currentPage

  page(baseURL + 'register', () => (currentPage = RegisterPage))
  page(baseURL + 'pomodoro', () => (currentPage = PomodoroPage))
  page(baseURL + 'new-task', () => (currentPage = NewTask))
  page(baseURL, () => (currentPage = LoginPage))

  page.start()
</script>

<svelte:component this={currentPage} />
