// pomodoro-vue/src/presentation/components/Input.vue
<template>
  <label id="normal" class="matter-textfield-standard">
    <input placeholder=" " v-model="value"/>
    <span>{{label}}</span>
  </label>
</template>

<script lang="ts">
  import Vue from 'vue';
  import Component from 'vue-class-component';

  const Base = Vue.extend({
    data() {
      return {
        value: ''
      }
    },
    props: {
      label: String
    },
    watch: {
      value() {
        this.$emit('value', this.value)
      }
    }
  })

  @Component
  export default class Button extends Base {
    
  }
</script>

<style scoped>
</style>

// pomodoro-react/src/presentation/basics/Input.js
import React, { useState } from 'react'

function Input(label, type) {
  const [value, setValue] = useState("");
  const input = <label id="normal" className="matter-textfield-standard">
    <input placeholder=" " value={value} onChange={e => setValue(e.target.value)} type={type} />
    <span>{label}</span>
  </label>
  return [value, setValue, input];
}

export default Input
