// svelte-pomodoro/src/presentation/core/components/Input.svelte
<script>
  export let inputType = 'text'
  export let label = ''
  export let onClick = (() => {})
</script>

<div class="form-group mb-3">
  <label for={label}>{label}:</label>
  <input on:change={(v) => onClick(v.target.value)} type={inputType} class="form-control" id={label} placeholder={label} name={label} />
</div>

// react-pomodoro/src/presentation/core/components/input.js
function Input(props) {
  return (
    <div className="form-group mb-3">
      <label for={props.label}>{props.label}:</label>
      <input type={props.inputType} className="form-control" id={props.label} placeholder={props.label} name={props.label} onChange={(e) => props.onClick(e.target.value) } />
    </div>
  )
}

export default Input
