// react-pomodoro/src/presentation/pomodoro/page/pomodoro_page.js
import React, { useState } from 'react'
import { Redirect } from 'react-router';

import './pomodoro_page.css';
import Button from '../../core/components/button'

import Logout from '../../../domain/use_cases/Logout'
import GetUserTasks from '../../../domain/use_cases/GetUserTasks'
import DeleteTask from '../../../domain/use_cases/DeleteTask'
import StartPomodoro from '../../../domain/use_cases/StartPomodoro'
import PausePomodoro from '../../../domain/use_cases/PausePomodoro'
import ResetPomodoro from '../../../domain/use_cases/ResetPomodoro'
import InvalidUser from '../../../exceptions/InvalidUser'
import User from '../../../domain/entities/User';
import { render } from '@testing-library/react';

class PomodoroPage extends React.Component {

  constructor() {
    super()
    
    const tokenLS = localStorage.getItem('token')
    const tokenSS = sessionStorage.getItem('token')

    this.state = {
      timer: 1500000, 
      pomodoroStage: 'Work', 
      shouldGoNewTask: false, 
      isLoged: tokenLS || tokenSS ? true : false,
      tasks: []
    }

    this.startTimer = this.startTimer.bind(this)
    this.resetTimer = this.resetTimer.bind(this)
    this.deleteTask = this.deleteTask.bind(this)
  }

  componentDidMount() {
    this.getTasks()
  }

  async logout() {
    try {
      const logout = new Logout()
      await logout.execute()
    } catch(e) {
      console.error(e)
    }
    this.setState({ isLoged: false })
  }

  async getTasks() {
    try {
      const getUserTasks = new GetUserTasks()
      const tasks = await getUserTasks.execute()
      this.setState({ tasks: tasks })
      console.log(this.state.tasks)
    } catch(e) {
      console.error(e)
    }
  }

  async deleteTask(taskId) {
    try {
      const deleteTask = new DeleteTask()
      await deleteTask.execute(taskId)
      const tasks = this.state.tasks.filter(e => {
        return e.id !== taskId
      })
      this.setState({ tasks: tasks })
    } catch(e) {
      console.error(e)
    }
  }
  
  parseMinutes() {
    const minutes = Math.floor((this.state.timer / 1000) / 60)
    return minutes < 10 ? `0${minutes}` : minutes
  }
  
  parseSeconds() {
    const seconds = Math.floor((this.state.timer / 1000) % 60)
    return seconds < 10 ? `0${seconds}` : seconds
  }
  
  startTimer() {
    const startPomodoro = new StartPomodoro()
    startPomodoro.execute((timer, stage) => {
      this.setState({
        timer: timer,
        pomodoroStage: stage
      })
    })
  }
  
  resetTimer() {
    const resetPomodoro = new ResetPomodoro()
    resetPomodoro.execute()
  }
  
  render() {
    if (!this.state.isLoged) {
      return <Redirect to="/"></Redirect>
    }

    return (
      <section className="pomodoro-page d-flex flex-column justify-content-start align-items-center">
        {
          this.state.shouldGoNewTask &&
          <Redirect to="/new-task"></Redirect>
        }
        <article className="timer w-100 p-3 mb-5 border d-flex justify-content-end">
          <Button label="Logout" onClick={() => this.logout()}></Button>
        </article>
        <article className="timer w-50 p-3 mb-3 border d-flex justify-content-center">
          <h3> {this.parseMinutes()} minutes {this.parseSeconds()} seconds </h3>
        </article>
        <article className="pomodoro-stage w-50 p-3 mb-3 border d-flex justify-content-center">
          Now its time to {this.state.pomodoroStage}
        </article>
        <article className="pomodoro-controls w-50 p-3 mb-3 border d-flex justify-content-around">
          <Button label="Start" onClick={() => this.startTimer()}></Button>
          <Button label="Reset" onClick={() => this.resetTimer()}></Button>
        </article>
        <article className="tasks w-50 p-3 border d-flex flex-column justify-content-around align-items-center">
          <Button label="New Task" onClick={() => this.setState({shouldGoNewTask: true})}></Button>
          {
            this.state.tasks?.map(e => {
              return (
                <article key={e.id} className="tasks-list w-100 mt-3 border p-2">
                  <span className="w-25"> <Button label="X" onClick={async () => await this.deleteTask(e.id)}></Button> </span>
                  <span className="w-75">{ e.description }</span>
                </article>
              )
            })
          }
        </article>
      </section>
    )
  }
}

export default PomodoroPage

// svelte-pomodoro/src/presentation/pomodoro/pages/PomodoroPage.svelte
<script>
  import page from 'page'
  import { onMount } from 'svelte'

  import Button from '../../core/components/Button.svelte'
  
  import Task from './../../../domain/entities/Task.js'
  import Logout from './../../../domain/use_cases/Logout.js'
  import CreateTask from './../../../domain/use_cases/CreateTask.js'
  import GetUserTasks from './../../../domain/use_cases/GetUserTasks.js'
  import DeleteTask from './../../../domain/use_cases/DeleteTask.js'
  import StartPomodoro from './../../../domain/use_cases/StartPomodoro.js'
  import ResetPomodoro from './../../../domain/use_cases/ResetPomodoro.js'
  import PausePomodoro from './../../../domain/use_cases/PausePomodoro.js'
  import InvalidUser from './../../../exceptions/InvalidUser.js'

  let timer = 1500000
  let pomodoroStage = 'word'
  let tasks = []

  function goToNewTask() {
    page('/new-task')
  }
  
  function goToLogin() {
    page('/')
  }

  function isAuthenticated() {
    const tokenLS = localStorage.getItem('token')
    const tokenSS = sessionStorage.getItem('token')

    const token = tokenLS || tokenSS

    console.log(token)
    
    if (!token) {
      goToLogin()
    }
  }

  function parseMinutes() {
    const minutes = Math.floor((timer / 1000) / 60)
    return minutes < 10 ? `0${minutes}` : minutes
  }

  function parseSeconds() {
    const seconds = Math.floor((timer / 1000) % 60)
    return seconds < 10 ? `0${seconds}` : seconds
  }

  function startTimer() {
    const startPomodoro = new StartPomodoro()
    startPomodoro.execute((timer, stage) => {
      timer = timer,
      pomodoroStage = stage
    })
  }

  function resetTimer() {
    const resetPomodoro = new ResetPomodoro()
    resetPomodoro.execute()
  }

  async function logout() {
    try {
      const logout = new Logout()
      await logout.execute()
    } catch(e) {
      console.error(e)
    }
    goToLogin()
  }

  async function getTasks() {
    try {
      const getUserTasks = new GetUserTasks()
      tasks = await getUserTasks.execute()
    } catch(e) {
      console.error(e)
    }
  }

  async function deleteTask(taskId) {
    try {
      const deleteTask = new DeleteTask()
      await deleteTask.execute(taskId)
      console.log(tasks.length)
      tasks = tasks.filter(e => {
        if (e.id != taskId) {
          return e
        }
      })
    } catch(e) {
      console.error(e)
    }
  }
  
  onMount(async () => {
    isAuthenticated()
    await getTasks()
  })
</script>

<style>
  .pomodoro-page {
    width: 100vw;
    min-height: 100vh;
  }
</style>

<section class="pomodoro-page d-flex flex-column justify-content-start align-items-center">
  <article class="timer w-100 p-3 mb-5 border d-flex justify-content-end">
    <Button label="Logout" onClick={logout} />
  </article>
  <article class="timer w-50 p-3 mb-3 border d-flex justify-content-center">
    <h3> { parseMinutes() } minutes { parseSeconds() } seconds </h3>
  </article>
  <article class="pomodoro-stage w-50 p-3 mb-3 border d-flex justify-content-center">
    Now its time to { pomodoroStage }
  </article>
  <article class="pomodoro-controls w-50 p-3 mb-3 border d-flex justify-content-around">
    <Button label="Start" onClick={startTimer} />
    <Button label="Reset" onClick={resetTimer} />
  </article>
  <article class="tasks w-50 p-3 border d-flex flex-column justify-content-around align-items-center">
    <Button label="New Task" onClick={goToNewTask} />
    {#each tasks as t (t.id)}
      <article class="tasks-list w-100 mt-3 border p-2">
        <span class="w-25"> <Button label="X" onClick={() => deleteTask(t.id)} /> </span>
        <span class="w-75">{t.description}</span>
      </article>
    {/each}
  </article>
</section>
