// pomodoro-vue/src/presentation/views/HomeWrapper.vue
<template>
  <div></div>
</template>

<script lang="ts">
  import Vue from 'vue';
  // import { State } from 'vuex-class';
  import Component from 'vue-class-component'

  @Component
  export default class HomeWrapper extends Vue {
    // @State('timer') state;

    mounted() {
      if (localStorage.getItem('token')) {
        this.$router.push('/pomodoro')
      } else {
        this.$router.push('/login')
      }
    }
  }
</script>

<style scoped>
</style>

// pomodoro-react/src/presentation/pages/HomeWrapper.js
import React from 'react'
// import { Redirect } from 'react-router';

import LoginPage from './LoginPage'
import PomodoroPage from './PomodoroPage'

function HomeWrapper() {
  if (localStorage.getItem('token')) {
    return <PomodoroPage></PomodoroPage>
  }
  return <LoginPage></LoginPage>
}

export default HomeWrapper
