// svelte-pomodoro/src/presentation/auth/pages/LoginPage.svelte
<script>
  import page from 'page'

  import Button from '../../core/components/Button.svelte'
  import Link from '../../core/components/Link.svelte'
  import Input from '../../core/components/Input.svelte'

  import Login from './../../../domain/use_cases/Login.js'
  import InvalidUser from './../../../exceptions/InvalidUser.js'
  import UserNotFound from './../../../exceptions/UserNotFound.js'

  let email = ''
  let password = ''
  let rememberMe = false
  let isModalOpen = false
  let modalMsg = ''

  function setEmail(value) {
    email = value
  }
  
  function setPassword(value) {
    password = value
  }

  function goToRegister() {
    page('/register')
  }

  function goToPomodoro() {
    page('/pomodoro')
  }

  function isAuthenticated() {
    const tokenLS = localStorage.getItem('token')
    const tokenSS = sessionStorage.getItem('token')
    
    if (tokenLS || tokenSS) {
      goToPomodoro()
    }
  }

  function openModal(msg) {
    isModalOpen = true
    modalMsg = msg
  }

  function closeModal() {
    isModalOpen = false
    modalMsg = ''
  }
  
  async function makeLogin() {
    try {
      const login = new Login()
      console.log(email)
      console.log(password)
      await login.execute(email, password, rememberMe)
      goToPomodoro()
    } catch(e) {
      if (e instanceof UserNotFound){
        openModal('User not found.')
        console.error()
      } else if(e instanceof InvalidUser) {
        openModal('Invalid user, verify your credentials.')
        console.error()
      }
    }
  }

  isAuthenticated()
</script>

<style>
  .login-page {
    width: 100vw;
    min-height: 100vh;
  }
</style>

<section class="login-page d-flex justify-content-center align-items-center">
  {#if isModalOpen}
    <div
      class="w-50 p-3 bg-white border zindex-modal position-absolute"
    >
      <p> { modalMsg } </p>
      <Button label="Close" onClick={() => closeModal()}></Button>
    </div>
  {/if}
  <article class="container w-25 p-3 border">
    <h2 class="mb-3">Login</h2>
    <Input inputType="email" label="Email" onClick={setEmail} />
    <Input inputType="password" label="Password" onClick={setPassword} />
    <div class="form-group form-check mb-3">
      <label class="form-check-label" for="remember">
        <input on:change={(v) => (rememberMe = v.target.value)} class="form-check-input" id="remember" type="checkbox" name="remember" /> Remember me
      </label>
    </div>
    <p> Don't have an account? <Link label="Register" onClick={goToRegister} /> now! </p>
    <Button label="Login" onClick={makeLogin} />
  </article>
</section>

// pomodoro-react/src/presentation/pages/LoginPage.js
import React, { useState } from 'react'
import { Redirect } from 'react-router';

import './LoginPage.css'
import Input from '../basics/Input'
import Button from '../basics/Button'
import Link from '../basics/Link'
import Modal from '../basics/Modal'

import isAuthenticated from '../../utils/isAuthenticated'
import Login from '../../domain/use_cases/Login'
import Email from '../../domain/entities/value_ojects/Email'
import Password from '../../domain/entities/value_ojects/Password'

async function login(email, password, setToPomodoroPage, setOpenModal) {
  const emailValidator = new Email(email)
  const passwordValidator = new Password(password)
  if (!emailValidator.isValid || !passwordValidator.isValid) {
    setOpenModal(true)
    return
  }

  const loginUseCase = new Login()
  try {
    await loginUseCase.execute(email, password)
    setToPomodoroPage(true)
  } catch (e) {
    setToPomodoroPage(false)
  }
}

function toPomodoro() {
  console.log('okok')
  return <Redirect to="/pomodoro" />
}

function LoginPage() {
  const [toPomodoroPage, setToPomodoroPage] = useState(false)
  const [openModal, setOpenModal, modal] = Modal('Invalid form data!', 'use a valid email and verify if the password is the same to both fields')
  const [email, setEmail, emailInput] = Input('email', 'email')
  const [password, setPassword, passwordInput] = Input('password', 'password')

  const onCLickLogin = () => login(email, password, setToPomodoroPage, setOpenModal)

  if (isAuthenticated() || toPomodoroPage) {
    return <Redirect to='/pomodoro' />
  }

  return <div id="login-page">
    {modal}
    <section id="login">
      <article>
        {emailInput}
        {passwordInput}
      </article>
      {Button('Enter', () => onCLickLogin())}
      <p className="or">or</p>
      <p>
        <Link href="/register-new-user" label="register"></Link> now!!! it's free!!!
      </p>
    </section>
  </div>
}

export default LoginPage
