// pomodoro-vue/src/components/Button.vue
<template>
  <button id="login-btn" class="matter-button-contained" v-on:click="onClick">{{label}}</button>
</template>

<script lang="ts">
  import Vue from 'vue';
  import Component from 'vue-class-component';

  const Props = Vue.extend({
    props: {
      label: String,
      onClick: Function
    }
  })

  @Component
  export default class Button extends Props {
    
  }
</script>

<style scoped>
</style>

// pomodoro-react-old/src/presentation/basics/Button.js
import React from 'react'

// import './Button.css'

class Button extends React.Component {
  constructor(props) {
    super()

    this.props = props
    this.state = {}
  }

  render() {
    return <button id="login-btn" className="matter-button-contained" type="submit" onClick={this.props.onClick}>{this.props.label}</button>
  }
}

export default Button
