// pomodoro-vue/src/presentation/components/Input.vue
<template>
  <label id="normal" class="matter-textfield-standard">
    <input placeholder=" " v-model="value"/>
    <span>{{label}}</span>
  </label>
</template>

<script lang="ts">
  import Vue from 'vue';
  import Component from 'vue-class-component';

  const Base = Vue.extend({
    data() {
      return {
        value: ''
      }
    },
    props: {
      label: String
    },
    watch: {
      value() {
        this.$emit('value', this.value)
      }
    }
  })

  @Component
  export default class Button extends Base {
    
  }
</script>

<style scoped>
</style>

// pomodoro-react-old/src/presentation/basics/Input.js
import React from 'react'

// import './Input.css'

class Input extends React.Component {
  constructor(props) {
    super()

    this.props = props
    this.static = {}
  }

  render() {
    return <label id="normal" className="matter-textfield-standard">
      <input placeholder=" "/>
      <span>{this.props.label}</span>
    </label>
  }
}

export default Input
