// pomodoro-vue/src/components/Link.vue
<template>
  <!-- <button id="login-btn" class="matter-button-contained">{{label}}</button> -->
  <a class="matter-link" v-on:click="() => $router.push(href)">{{label}}</a>
</template>

<script lang="ts">
  import Vue from 'vue';
  import Component from 'vue-class-component';

  const Props = Vue.extend({
    props: {
      label: String,
      href: String
    }
  })

  @Component
  export default class Link extends Props {
    
  }
</script>

<style scoped>
  a {
    font-size: large;
  }
</style>

// pomodoro-react-old/src/presentation/basics/Link.js
import React from 'react'
import { Link } from 'react-router-dom'

// import './Button.css'

import "./Link.css"

class LinkComponent extends React.Component {
  constructor(props) {
    super()

    this.props = props
    this.state = {}
  }

  render() {
    // return <a className="matter-link" href={this.props.href}>{this.props.label}</a>
    return <Link to={this.props.href} className="matter-link">{this.props.label}</Link>
  }
}

export default LinkComponent
