// pomodoro-svelte/src/components/basics/Timer.svelte
<script>
  import page, { redirect, start } from 'page';

  import { onDestroy } from 'svelte';

  import Button from '../basics/Button.svelte'
  import Input from '../basics/Input.svelte'
  import Timer from '../basics/Timer.svelte'

  let initialTimer = null
  let currentTimer = null
  let pomodoroCurrentStage = 0
  let shortRestDiv = false
  let longRestDiv = false
  let workTimeDiv = true

  function calculateTimerMinuterSeconds(currentTimer, initialTimer) {
    const timePassed = currentTimer - initialTimer

    const seconds = Math.floor((timePassed / 1000) % 60)
    const minutes = timePassed > 60000 ? Math.floor(timePassed / 60000) : 0

    return [minutes, seconds]
  }

  function definePomodoroStage() {
    const [minutes] = calculateTimerMinuterSeconds(currentTimer, initialTimer)

    if (minutes === 5 && pomodoroCurrentStage % 2 === 1) {
        pomodoroCurrentStage: pomodoroCurrentStage + 1,
        shortRestDiv = '',
        workTimeDiv = 'pomodoro-stage-active'
    } else if (minutes === 15
      && pomodoroCurrentStage === 7) {
        pomodoroCurrentStage = 0,
        shortRestDiv = '',
        workTimeDiv = 'pomodoro-stage-active'
    } else if (minutes === 25
      && pomodoroCurrentStage === 6) {
        pomodoroCurrentStage = 0,
        longRestDiv = 'pomodoro-stage-active',
        workTimeDiv = ''
    } else if (minutes === 25) {
        pomodoroCurrentStage = pomodoroCurrentStage + 1,
        shortRestDiv = 'pomodoro-stage-active',
        workTimeDiv = ''
    }
  }

  function startTimer() {
    initialTimer = new Date()

    currentTimer = setInterval(
      () => {
        console.log('okok')
        tick()
        definePomodoroStage()
      },
      1000
    );
  }

  function stopTimer() {
    clearInterval(currentTimer)
  }

  function tick() {
    currentTimer = new Date()
  }

  function parseTick(currentTimer, initialTimer) {
    const [minutes, seconds] = calculateTimerMinuterSeconds(currentTimer, initialTimer)

    return `${minutes} : ${seconds < 0 ? 0 : seconds}`
  }

  $: displayTime = parseTick(currentTimer, initialTimer)

  startTimer()
</script>

<style>
  #timer {
    padding: 1rem 0 0 0;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .pomodoro-stages {
    width: 100vw;
    height: 7rem;
    display: flex;
    flex-direction: row;
    justify-content: space-around;
    align-items: center;
  }

  .pomodoro-stages .pomodoro-stage {
    width: 7rem;
    height: 5rem;
    display: flex;
    justify-content: space-around;
    align-items: center;
    background-color: lightpink;
    font-weight: bold;
  }

  .pomodoro-stages .pomodoro-stage-active {
    background-color: tomato !important;
    color: white;
  }
</style>

<div id="timer">
  <p>{displayTime}</p>

  <div class="pomodoro-stages">
    <div id="pomodoro-short-rest" class="pomodoro-stage" class:shortRestDiv={'pomodoro-stage-active'}>Short Rest</div>
    <div id="pomodoro-long-rest" class="pomodoro-stage" class:longRestDiv={'pomodoro-stage-active'} >Long Rest</div>
    <div id="pomodoro-work-time" class="pomodoro-stage" class:workTimeDiv={'pomodoro-stage-active'} >Work Time</div>
  </div>

  <div id="time-bar" />
</div>

// pomodoro-vue/src/views/Timer.vue
<template>
  <section id="timer-page">
    <p>{parseTick()}</p>

    <div className="pomodoro-stages">
      <div id="pomodoro-short-rest" class="pomodoro-stage" :class="{'pomodoro-stage-active': shortRestDiv}">Short Rest</div>
      <div id="pomodoro-long-rest" class="pomodoro-stage" :class="{'pomodoro-stage-active': longRestDiv}" >Long Rest</div>
      <div id="pomodoro-work-time" class="pomodoro-stage" :class="{'pomodoro-stage-active': workTimeDiv}" >Work Time</div>
    </div>

    <div id="time-bar">

    </div>

    <div className="tasks-indicator">
      <p className="total-tasks">Total tasks: {toDoTasks.length}</p>
      <p className="tasksdone-">Done tasks: {doneTasks}</p>
    </div>

    <Input label="New Task text" :onChange="updateTaskText" type="text" />

    <Button label="Create new task" :onClick="() => {}" />
  </section>
</template>

<script>
  import { mapGetters, mapMutations } from 'vuex'

  import Button from '../basics/Button.svelte'
  import Figure from '../basics/Figure.svelte'
  import Input from '../basics/Input.svelte'

  export default {
    name: 'Timer',
    components: {
      'app-button': Button,
      'app-input': Input
    },
    computed: {
      ...mapGetters([
        'parseTick'
      ])
    },
    methods: {
      ...mapMutations([
        'startTimer',
        'stopTimer',
        'tick'
      ])
    }
  }
</script>

<style scoped>
  #timer-page {
    min-height: 100vh;
    min-width: 100vw;
    padding: 1rem 0 0 0;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .pomodoro-stages {
    width: 100vw;
    height: 7rem;
    display: flex;
    flex-direction: row;
    justify-content: space-around;
    align-items: center;
  }

  .pomodoro-stages .pomodoro-stage {
    width: 7rem;
    height: 5rem;
    display: flex;
    justify-content: space-around;
    align-items: center;
    background-color: lightpink;
    font-weight: bold;
  }

  .pomodoro-stages .pomodoro-stage-active {
    background-color: tomato !important;
    color: white;
  }

  .tasks-indicator {
    width: 100vw;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
    padding: 0 5vw 0 5vw;
    box-sizing: border-box;
  }
</style>
